## Importing Libraries and Data ##

In [7]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
data = pd.read_csv(r"C:\Users\anirv\Downloads\credit_risk_dataset.csv\credit_risk_dataset.csv")
print(f"Data Loaded: {data.shape[0]} rows, {data.shape[1]} columns")

Data Loaded: 32581 rows, 12 columns

In [8]:
pd.options.display.float_format = '{:,.2f}'.format

In [9]:
import pandas as pd
from sqlalchemy import create_engine

data = pd.read_csv(r"C:\Users\anirv\Downloads\credit_risk_dataset.csv\credit_risk_dataset.csv")

data.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.00,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.00,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.00,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.00,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.00,MEDICAL,C,35000,14.27,1,0.55,Y,4

## Exporting data to PostgreSQL ##

In [1]:
!pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\anirv\anaconda3\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\anirv\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\anirv\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\anirv\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [3]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql+psycopg2://postgres:root@localhost:5432/postgres"
)

with engine.connect() as conn:

    conn.execute(text("COMMIT"))

    try:
        conn.execute(text("""
        CREATE DATABASE credit_risk_db;
        """))

        print("Database created successfully")

    except Exception as e:
        print("Database may already exist")

Database created successfully

In [4]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine(
    "postgresql+psycopg2://postgres:root@localhost:5432/credit_risk_db")

print("Connected successfully")

Connected successfully

In [10]:
data.to_sql(name='analysis',con=engine,if_exists='replace',index=False)

print("Table loaded successfully")

Table loaded successfully

In [11]:
pd.read_sql("""
SELECT *
FROM analysis
LIMIT 5;
""", engine)

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.00,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.00,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.00,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.00,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.00,MEDICAL,C,35000,14.27,1,0.55,Y,4

## Creating Tables ##

In [12]:
from sqlalchemy import create_engine, text
import pandas as pd

# CONNECT TO POSTGRESQL DATABASE
engine = create_engine(
    "postgresql+psycopg2://postgres:root@localhost:5432/credit_risk_db")

# ADD UNIQUE RECORD ID
data = data.reset_index(drop=True)

data['record_id'] = data.index + 1

# LOAD RAW DATA
data.to_sql(name='analysis',con=engine,if_exists='replace',index=False)

print("Analysis table created")

# CREATE NORMALIZED TABLES
with engine.connect() as conn:

    # DROP OLD TABLES
    conn.execute(text("DROP TABLE IF EXISTS loans CASCADE"))
    conn.execute(text("DROP TABLE IF EXISTS persons CASCADE"))
    conn.execute(text("DROP TABLE IF EXISTS home_ownership CASCADE"))
    conn.execute(text("DROP TABLE IF EXISTS loan_intents CASCADE"))
    conn.execute(text("DROP TABLE IF EXISTS loan_grades CASCADE"))
    conn.execute(text("DROP TABLE IF EXISTS credit_history CASCADE"))

    # HOME OWNERSHIP DIMENSION
    conn.execute(text("""
    CREATE TABLE home_ownership AS
    SELECT DISTINCT
        DENSE_RANK() OVER(
            ORDER BY person_home_ownership
        ) AS home_ownership_id,
        person_home_ownership AS ownership_type
    FROM analysis;
    """))

    # LOAN INTENTS DIMENSION
    conn.execute(text("""
    CREATE TABLE loan_intents AS
    SELECT DISTINCT
        DENSE_RANK() OVER(
            ORDER BY loan_intent
        ) AS intent_id,
        loan_intent
    FROM analysis;
    """))

    # LOAN GRADES DIMENSION
    conn.execute(text("""
    CREATE TABLE loan_grades AS
    SELECT DISTINCT
        DENSE_RANK() OVER(
            ORDER BY loan_grade
        ) AS grade_id,
        loan_grade
    FROM analysis;
    """))

    # PERSONS TABLE
    conn.execute(text("""
    CREATE TABLE persons AS
    SELECT
        a.record_id AS person_id,
        a.person_age,
        a.person_income,
        a.person_emp_length,
        h.home_ownership_id
    FROM analysis a
    JOIN home_ownership h
        ON a.person_home_ownership = h.ownership_type;
    """))

    # CREDIT HISTORY TABLE
    conn.execute(text("""
    CREATE TABLE credit_history AS
    SELECT
        record_id AS credit_hist_id,
        cb_person_default_on_file,
        cb_person_cred_hist_length
    FROM analysis;
    """))

    # LOANS FACT TABLE
    conn.execute(text("""
    CREATE TABLE loans AS
    SELECT
        a.record_id AS loan_id,
        a.record_id AS person_id,
        a.record_id AS credit_hist_id,
        i.intent_id,
        g.grade_id,
        a.loan_amnt,
        a.loan_int_rate,
        a.loan_status,
        a.loan_percent_income
    FROM analysis a
    JOIN loan_intents i
        ON a.loan_intent = i.loan_intent
    JOIN loan_grades g
        ON a.loan_grade = g.loan_grade;
    """))

    conn.commit()

print("All tables created successfully")

# CHECK TABLES
tables = pd.read_sql("""

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public';

""", engine)

print(tables)

Analysis table created
All tables created successfully
       table_name
0        analysis
1  home_ownership
2    loan_intents
3     loan_grades
4         persons
5  credit_history
6           loans

## Core Banking KPI's ##

# >Total Loans #

In [28]:
pd.read_sql("""
SELECT
    COUNT(*) AS total_loans
FROM loans;
""", engine)

   total_loans
0        32581

# >Total Loan Exposure #

In [29]:
pd.read_sql("""
SELECT
    ROUND(SUM(loan_amnt)::numeric, 2) AS total_exposure
FROM loans;
""", engine)

   total_exposure
0  312,431,300.00

# >Average Loan Amount #

In [32]:
pd.read_sql("""
SELECT
    ROUND(AVG(loan_amnt)::numeric, 2) AS Avg_Loan_amt
FROM loans;
""", engine)

   avg_loan_amt
0      9,589.37

# >Average Interest Rate #

In [34]:
pd.read_sql("""
SELECT
    ROUND(AVG(loan_int_rate)::numeric, 2) AS Avg_intrest_rate
FROM loans;
""", engine)

   avg_intrest_rate
0             11.01

# >Overall Default Rate #

In [35]:
pd.read_sql("""
SELECT
    COUNT(*) AS total_loans,
    SUM(loan_status) AS total_defaults,
    ROUND((100 * AVG(loan_status))::numeric, 2) AS default_rate
FROM loans;
""", engine)

   total_loans  total_defaults  default_rate
0        32581        7,108.00         21.82

# Risk KPI's #

# >Loan Grade Risk Analysis #

In [37]:
pd.read_sql("""
SELECT
    lg.loan_grade,
    COUNT(*) AS total_loans,
    SUM(l.loan_status) AS defaults,
    ROUND((100 * AVG(l.loan_status))::numeric, 2) AS default_rate,
    ROUND(AVG(l.loan_int_rate)::numeric, 2) AS avg_interest_rate
FROM loans l
JOIN loan_grades lg
    ON l.grade_id = lg.grade_id
GROUP BY lg.loan_grade
ORDER BY default_rate DESC;
""", engine)

  loan_grade  total_loans  defaults  default_rate  avg_interest_rate
0          G           64     63.00         98.44              20.25
1          F          241    170.00         70.54              18.61
2          E          964    621.00         64.42              17.01
3          D         3626  2,141.00         59.05              15.36
4          C         6458  1,339.00         20.73              13.46
5          B        10451  1,701.00         16.28              11.00
6          A        10777  1,073.00          9.96               7.33

# >Loan Intent Risk Analysis

In [38]:
pd.read_sql("""
SELECT
    li.loan_intent,
    COUNT(*) AS total_loans,
    SUM(l.loan_status) AS defaults,
    ROUND((100 * AVG(l.loan_status))::numeric, 2) AS default_rate
FROM loans l
JOIN loan_intents li
    ON l.intent_id = li.intent_id
GROUP BY li.loan_intent
ORDER BY default_rate DESC;
""", engine)

         loan_intent  total_loans  defaults  default_rate
0  DEBTCONSOLIDATION         5212  1,490.00         28.59
1            MEDICAL         6071  1,621.00         26.70
2    HOMEIMPROVEMENT         3605    941.00         26.10
3           PERSONAL         5521  1,098.00         19.89
4          EDUCATION         6453  1,111.00         17.22
5            VENTURE         5719    847.00         14.81

# >Home Ownership Risk Analysis

In [39]:
pd.read_sql("""
SELECT
    h.ownership_type,
    COUNT(*) AS total_loans,
    SUM(l.loan_status) AS defaults,
    ROUND((100 * AVG(l.loan_status))::numeric, 2) AS default_rate
FROM loans l
JOIN persons p
    ON l.person_id = p.person_id
JOIN home_ownership h
    ON p.home_ownership_id = h.home_ownership_id
GROUP BY h.ownership_type
ORDER BY default_rate DESC;
""", engine)

  ownership_type  total_loans  defaults  default_rate
0           RENT        16446  5,192.00         31.57
1          OTHER          107     33.00         30.84
2       MORTGAGE        13444  1,690.00         12.57
3            OWN         2584    193.00          7.47

# >Employment Length Risk Analysis

In [40]:
pd.read_sql("""
SELECT
    CASE
        WHEN person_emp_length < 2 THEN '0-2 Years'
        WHEN person_emp_length < 5 THEN '2-5 Years'
        WHEN person_emp_length < 10 THEN '5-10 Years'
        ELSE '10+ Years'
    END AS employment_group,
    COUNT(*) AS total_people,
    ROUND(AVG(l.loan_status)::numeric * 100, 2) AS default_rate
FROM persons p
JOIN loans l
    ON p.person_id = l.person_id
GROUP BY employment_group
ORDER BY default_rate DESC;
""", engine)

  employment_group  total_people  default_rate
0        0-2 Years          7020         27.82
1        2-5 Years         10179         22.53
2        10+ Years          4520         19.40
3       5-10 Years         10862         18.27

# >Credit History Risk Analysis

In [41]:
pd.read_sql("""
SELECT
    CASE
        WHEN cb_person_cred_hist_length < 5 THEN 'Short History'
        WHEN cb_person_cred_hist_length < 10 THEN 'Medium History'
        ELSE 'Long History'
    END AS credit_history_group,
    COUNT(*) AS total_people,
    ROUND(
        AVG(l.loan_status)::numeric * 100, 2) AS default_rate
FROM credit_history c
JOIN loans l
    ON c.credit_hist_id = l.credit_hist_id
GROUP BY credit_history_group
ORDER BY default_rate DESC;
""", engine)

  credit_history_group  total_people  default_rate
0        Short History         17833         22.72
1         Long History          5312         20.75
2       Medium History          9436         20.71

# CUSTOMER KPIs

# >Income vs Loan Analysis

In [42]:
pd.read_sql("""
SELECT
    CASE
        WHEN p.person_income < 30000 THEN 'Low Income'
        WHEN p.person_income < 70000 THEN 'Middle Income'
        ELSE 'High Income'
    END AS income_group,
    COUNT(*) AS total_people,
    ROUND(AVG(l.loan_amnt)::numeric, 2) AS avg_loan_amount,
    ROUND(AVG(l.loan_status)::numeric * 100, 2) AS default_rate
FROM persons p
JOIN loans l
    ON p.person_id = l.person_id
GROUP BY income_group
ORDER BY default_rate DESC;
""", engine)

    income_group  total_people  avg_loan_amount  default_rate
0     Low Income          3669         5,149.82         47.07
1  Middle Income         17864         8,615.70         23.46
2    High Income         11048        12,638.10         10.77

# >Age Group Analysis

In [43]:
pd.read_sql("""
SELECT
    CASE
        WHEN p.person_age < 25 THEN '18-24'
        WHEN p.person_age < 35 THEN '25-34'
        WHEN p.person_age < 45 THEN '35-44'
        ELSE '45+'
    END AS age_group,
    COUNT(*) AS total_people,
    ROUND(AVG(l.loan_amnt)::numeric, 2) AS avg_loan_amount,
    ROUND(AVG(l.loan_status)::numeric * 100, 2) AS default_rate
FROM persons p
JOIN loans l
    ON p.person_id = l.person_id
GROUP BY age_group
ORDER BY default_rate DESC;
""", engine)

  age_group  total_people  avg_loan_amount  default_rate
0     18-24         12315         9,068.77         23.22
1       45+           760        10,036.58         22.50
2     25-34         16180         9,892.27         20.97
3     35-44          3326         9,941.27         20.57

# Advanced Risk & Portfolio Analytics

# >Loan-to-Income Risk Analysis

In [44]:
pd.read_sql("""
SELECT
    CASE
        WHEN loan_percent_income < 0.20 THEN 'Low Burden'
        WHEN loan_percent_income < 0.40 THEN 'Medium Burden'
        ELSE 'High Burden'
    END AS loan_burden,
    COUNT(*) AS total_loans,
    ROUND(AVG(loan_int_rate)::numeric, 2) AS avg_interest_rate,
    ROUND(AVG(loan_status)::numeric * 100, 2) AS default_rate
FROM loans
GROUP BY loan_burden
ORDER BY default_rate DESC;
""", engine)

     loan_burden  total_loans  avg_interest_rate  default_rate
0    High Burden         1335              11.60         73.63
1  Medium Burden         9767              11.52         33.23
2     Low Burden        21479              10.74         13.40

# >Exposure at Risk #

In [45]:
pd.read_sql("""
SELECT
    ROUND(SUM(CASE
                WHEN loan_status = 1
                THEN loan_amnt
                ELSE 0
            END)::numeric, 2) AS exposure_at_risk
FROM loans;
""", engine)

   exposure_at_risk
0     77,125,375.00

# >High-Risk Borrower Segmentation

In [46]:
pd.read_sql("""
SELECT
    CASE
        WHEN loan_percent_income >= 0.40
             OR loan_int_rate >= 15
        THEN 'High Risk'
        WHEN loan_percent_income >= 0.25
        THEN 'Medium Risk'
        ELSE 'Low Risk'
    END AS risk_segment,
    COUNT(*) AS total_loans,
    ROUND(AVG(loan_status)::numeric * 100, 2) AS default_rate,
    ROUND(AVG(loan_amnt)::numeric, 2) AS avg_loan_amount
FROM loans
GROUP BY risk_segment
ORDER BY default_rate DESC;
""", engine)

  risk_segment  total_loans  default_rate  avg_loan_amount
0    High Risk         4599         61.38        12,861.68
1  Medium Risk         4855         39.18        13,774.09
2     Low Risk        23127         10.30         8,060.16

# >Portfolio Distribution Analysis

In [47]:
pd.read_sql("""
SELECT
    li.loan_intent,
    COUNT(*) AS total_loans,
    ROUND(SUM(l.loan_amnt)::numeric, 2) AS total_exposure,
    ROUND(AVG(l.loan_amnt)::numeric, 2) AS avg_loan_amount
FROM loans l
JOIN loan_intents li
    ON l.intent_id = li.intent_id
GROUP BY li.loan_intent
ORDER BY total_exposure DESC;
""", engine)

         loan_intent  total_loans  total_exposure  avg_loan_amount
0          EDUCATION         6453   61,191,725.00         9,482.68
1            MEDICAL         6071   56,214,925.00         9,259.58
2            VENTURE         5719   54,809,625.00         9,583.78
3           PERSONAL         5521   52,856,800.00         9,573.77
4  DEBTCONSOLIDATION         5212   50,008,550.00         9,594.89
5    HOMEIMPROVEMENT         3605   37,349,675.00        10,360.52

In [48]:
data.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length,record_id
0,22,59000,RENT,123.00,PERSONAL,D,35000,16.02,1,0.59,Y,3,1
1,21,9600,OWN,5.00,EDUCATION,B,1000,11.14,0,0.10,N,2,2
2,25,9600,MORTGAGE,1.00,MEDICAL,C,5500,12.87,1,0.57,N,3,3
3,23,65500,RENT,4.00,MEDICAL,C,35000,15.23,1,0.53,N,2,4
4,24,54400,RENT,8.00,MEDICAL,C,35000,14.27,1,0.55,Y,4,5

# >Loan Intent by Age Group #

In [52]:
pd.read_sql("""

SELECT
    CASE
        WHEN c.person_age BETWEEN 18 AND 25 THEN '18-25'
        WHEN c.person_age BETWEEN 26 AND 35 THEN '26-35'
        WHEN c.person_age BETWEEN 36 AND 45 THEN '36-45'
        WHEN c.person_age BETWEEN 46 AND 60 THEN '46-60'
        ELSE '60+'
    END AS age_group,
    COUNT(DISTINCT c.person_id) AS total_people,
    ROUND(AVG(c.person_income),2) AS avg_income,
    MODE() WITHIN GROUP (
        ORDER BY b.loan_intent
    ) AS most_common_loan_intent
FROM loans a
JOIN loan_intents b
ON a.intent_id = b.intent_id
JOIN persons c
ON a.person_id = c.person_id
GROUP BY age_group
ORDER BY total_people DESC;
""", engine)

  age_group  total_people  avg_income most_common_loan_intent
0     18-25         15352   58,958.47               EDUCATION
1     26-35         13763   70,389.65                 MEDICAL
2     36-45          2814   77,093.39                 MEDICAL
3     46-60           582   84,029.88                PERSONAL
4       60+            70  186,217.10                PERSONAL